import HeaderTop from "../components/HeaderTop";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeaderMain from "../components/HeaderMain";
import Navbar from "../components/Navbar";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import MobNavbar from "../components/MobNavbar";
import Footer from "../components/Footer";

import "bootstrap/dist/css/bootstrap.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Almari",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <main>
      <HeaderTop />
      <HeaderMain />
      <Navbar />
      <MobNavbar />
      {children}
      <Footer />
      <ToastContainer />
    </main>
  );
}
